helloworld_before_refactor/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :subscriptions
  resources :contact_forms

  root 'modules#index', as: :modules

   get  '/mod_user' => 'application#mod_user'

   post "/controls/new" => "subscriptions#create"

   get '/subscribe' => 'controls#new'
   post '/subscribe' => 'controls#new'

   get '/subscribers' => 'controls#index'

   post '/subscriptions/new' => 'subscriptions#create'

   get '/product' => 'products#show'

   get ':id', to: 'modules#show', as: :module

end

helloworld_before_refactor/app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
	belongs_to :subject

	validates :full_name, presence: true
	validates :order_num, presence: true, length: { minimum: 2 }
	validates :comments, presence: true
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "invalid format"}, presence: true
end

helloworld_before_refactor/app/models/control.rb
class Control < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	attr_accessor :marker

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/product.rb
class Product < ActiveRecord::Base
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :contact_forms
end

helloworld_before_refactor/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/sys_rln_sya_sym.rb
class SysRlnSyaSym < ActiveRecord::Base
	self.table_name = "sys_rln_sya_sym"
	belongs_to :sys_sym_module, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	belongs_to :sys_sya_account, :foreign_key => :rln_sya_id, :primary_key => :sya_id
end

helloworld_before_refactor/app/models/sys_sla_log_action.rb
class SysSlaLogAction < ActiveRecord::Base
	self.table_name = "sys_sla_log_action"
end

helloworld_before_refactor/app/models/sys_sle_log_error.rb
class SysSleLogError < ActiveRecord::Base
	self.table_name = "sys_sle_log_error"
end

helloworld_before_refactor/app/models/sys_sls_log_security.rb
class SysSlsLogSecurity < ActiveRecord::Base
	self.table_name = "sys_sls_log_security"
end

helloworld_before_refactor/app/models/sys_ste_site.rb
class SysSteSite < ActiveRecord::Base
	self.table_name = "sys_ste_site"
end

helloworld_before_refactor/app/models/sys_stx_text_label.rb
class SysStxTextLabel < ActiveRecord::Base
	self.table_name = "sys_stx_text_label"
end

helloworld_before_refactor/app/models/sys_sya_account.rb
class SysSyaAccount < ActiveRecord::Base
	self.table_name = "sys_sya_account"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sya_id, :primary_key => :sya_id
	has_many :sys_sym_modules, :through => :sys_rln_sya_syms
end

helloworld_before_refactor/app/models/sys_sym_module.rb
class SysSymModule < ActiveRecord::Base
	self.table_name = "sys_sym_module"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	has_many :sys_sya_accounts, :through => :sys_rln_sya_syms

	def to_param
		"module#{id}"
	end

end

helloworld_before_refactor/app/models/sys_syw_whitelist.rb
class SysSywWhitelist < ActiveRecord::Base
	self.table_name = "sys_syw_whitelist"
end

helloworld_before_refactor/app/models/tst_dmo_demo.rb
class TstDmoDemo < ActiveRecord::Base
	self.table_name = "tst_dmo_demo"
end

helloworld_before_refactor/app/models/tst_exp_example.rb
class TstExpExample < ActiveRecord::Base
	self.table_name = "tst_exp_example"
end

helloworld_before_refactor/app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  before_action :set_control, only: [:show]


  def new
      @control = Control.new
      @params = params

    if params['control'] && params['control']['marker'] == 'review'
      @control = Control.new(control_params)
      @control.save 
    
      url = request.url + "?done=true"
      redirect_to(url)
    end
  end

  def index
    @controls = Control.all
  end

private

  def set_control
    @control = Control.find(params[:id])
  end
   
  def control_params
    params.require(:control).permit(:name, :email, :ost_id, :list, :marker)
  end

end

helloworld_before_refactor/app/helpers/application_helper.rb
module ApplicationHelper
	
end

helloworld_before_refactor/app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

helloworld_before_refactor/app/helpers/controls_helper.rb
module ControlsHelper
end

helloworld_before_refactor/app/helpers/pages_helper.rb
module PagesHelper
end

helloworld_before_refactor/app/helpers/products_helper.rb
module ProductsHelper
end

helloworld_before_refactor/app/helpers/sql_query_helper.rb
module SqlQueryHelper
	def form_query
		sql = "
		  SELECT * 
		  FROM contact_forms
		"
        @forms = ActiveRecord::Base.connection.exec_query(sql)
	end
end

helloworld_before_refactor/app/views/controls/_form.html.erb
<% name = "" %>
<% email = "" %>
<% list = "" %>

<% if @params['control'] %>
	<% name = @params['control']['name']%>
	<% email = @params['control']['email']%>
	<% list = @params['control']['list']%>
<% end %>

<% if request.get? && params['done'] && params['done'] == 'true' %>

	<%# Done %>	

	<p>
	We're Done!
	</p><br>

	<%= params %>
	

<% elsif request.post? && params['control']['marker'] == 'info' %>

	<%# Review %>

	<h2> Confirm Control Create</h2><br>

	<form action="/subscribe" method="post" id="new_control" class="new_control">

		<input type="hidden" name="control[marker]" id="control_marker" value="review">
		<input type="hidden" name="control[list]" id="control_list" value="With Name">
		<input type="hidden" name="control[name]" id="control_name" value="<%= name %>">
		<input type="hidden" name="control[email]" id="control_email" value="<%= email %>">
		
		<p>Your name is:<%= " " + name %></p>

		<p>Your email is:<%= " " + email %></p>

		<p>Your List is:<%= " " + list %></p>

		<div class="actions">
	      <input type="submit" name="commit" value="Confirm Control Create">
	    </div>

	</form><br>

	<%# Go Back %>

	<form action="/subscribe" method="post" id="new_control" class="new_control">

		<input type="hidden" name="control[marker]" id="control_marker" value="change">
		<input type="hidden" name="control[list]" id="control_list" value="With Name">
		<input type="hidden" name="control[name]" id="control_name" value="<%= name %>">
		<input type="hidden" name="control[email]" id="control_email" value="<%= email %>">

		<div class="actions">
	      <input type="submit" name="commit" value="Go Back">
	    </div>

	</form>

	<%= @params %>

<% else %>

	<%# Default %>

	<h2>Create Control</h2>

		<form action="/subscribe" method="post" id="new_control" class="new_control">

			<input type="hidden" name="control[marker]" id="control_marker" value="info">
			<input type="hidden" name="control[list]" id="control_list" value="With Name">

		   <div class="field">
		     
		     <label for="control_name">
		       Name
		     </label><br>

	     	 <input type="text" name="control[name]" id="control_name" value='<%= name %>'>

		   </div>

		   <div class="field">
		     
		     <label for="control_email">
		       Email
		     </label><br>

	     	 <input type="text" name="control[email]" id="control_name" value='<%= email %>'>

		   </div>
		   
		   <div class="actions">
		     <input type="submit" name="commit" value="Create Control">
		   </div>

		</form>
		<%= @params %>

<% end %>

helloworld_before_refactor/app/views/controls/done.html.erb
<p>
	We're Done!
</p><br>

<%= params %>

helloworld_before_refactor/app/views/controls/index.html.erb
<% @controls = Control.all %>

<% @controls.each do |x| %>
	<p>
		<%= x.name %>
	</p>
<% end %>

<br>

<p><%= link_to 'Make another', subscribe_path %></p>

helloworld_before_refactor/app/views/controls/new.html.erb
<%= render 'form' %>
	
<%= link_to 'Back', subscribers_path %><br>

		

helloworld_before_refactor/app/views/controls/show.html.erb
<h1>Your Created Control Name</h1>

<p><%= @control.name %></p>

<%= link_to 'All controls', subscribers_path %><br>

helloworld_before_refactor/app/views/controls/submitted.html.erb
<p>Form was Submitted!</p>