helloworld_before_refactor/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :subscriptions
  resources :contact_forms

  root 'modules#index', as: :modules

   get  '/mod_user' => 'application#mod_user'

   post "/controls/new" => "subscriptions#create"

   get '/subscribe' => 'controls#new'
   post '/subscribe' => 'controls#new'

   get '/subscribers' => 'controls#index'

   post '/subscriptions/new' => 'subscriptions#create'

   get '/product' => 'products#show'

   get ':id', to: 'modules#show', as: :module

end

helloworld_before_refactor/app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
	belongs_to :subject

	validates :full_name, presence: true
	validates :order_num, presence: true, length: { minimum: 2 }
	validates :comments, presence: true
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "invalid format"}, presence: true
end

helloworld_before_refactor/app/models/control.rb
class Control < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	attr_accessor :marker

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/product.rb
class Product < ActiveRecord::Base
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :contact_forms
end

helloworld_before_refactor/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/sys_rln_sya_sym.rb
class SysRlnSyaSym < ActiveRecord::Base
	self.table_name = "sys_rln_sya_sym"
	belongs_to :sys_sym_module, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	belongs_to :sys_sya_account, :foreign_key => :rln_sya_id, :primary_key => :sya_id
end

helloworld_before_refactor/app/models/sys_sla_log_action.rb
class SysSlaLogAction < ActiveRecord::Base
	self.table_name = "sys_sla_log_action"
end

helloworld_before_refactor/app/models/sys_sle_log_error.rb
class SysSleLogError < ActiveRecord::Base
	self.table_name = "sys_sle_log_error"
end

helloworld_before_refactor/app/models/sys_sls_log_security.rb
class SysSlsLogSecurity < ActiveRecord::Base
	self.table_name = "sys_sls_log_security"
end

helloworld_before_refactor/app/models/sys_ste_site.rb
class SysSteSite < ActiveRecord::Base
	self.table_name = "sys_ste_site"
end

helloworld_before_refactor/app/models/sys_stx_text_label.rb
class SysStxTextLabel < ActiveRecord::Base
	self.table_name = "sys_stx_text_label"
end

helloworld_before_refactor/app/models/sys_sya_account.rb
class SysSyaAccount < ActiveRecord::Base
	self.table_name = "sys_sya_account"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sya_id, :primary_key => :sya_id
	has_many :sys_sym_modules, :through => :sys_rln_sya_syms
end

helloworld_before_refactor/app/models/sys_sym_module.rb
class SysSymModule < ActiveRecord::Base
	self.table_name = "sys_sym_module"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	has_many :sys_sya_accounts, :through => :sys_rln_sya_syms

	def to_param
		"module#{id}"
	end

end

helloworld_before_refactor/app/models/sys_syw_whitelist.rb
class SysSywWhitelist < ActiveRecord::Base
	self.table_name = "sys_syw_whitelist"
end

helloworld_before_refactor/app/models/tst_dmo_demo.rb
class TstDmoDemo < ActiveRecord::Base
	self.table_name = "tst_dmo_demo"
end

helloworld_before_refactor/app/models/tst_exp_example.rb
class TstExpExample < ActiveRecord::Base
	self.table_name = "tst_exp_example"
end

helloworld_before_refactor/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end


  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    
    def set_product
      if params['pID']
        @product = Product.find(params[:pID])
      else
        @product = Product.find(params[:id])
      end
    end

    def product_params
      params.require(:product).permit(:name, :sku, :description, :ost_id, :priority)
    end
    
end

helloworld_before_refactor/app/helpers/application_helper.rb
module ApplicationHelper
	
end

helloworld_before_refactor/app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

helloworld_before_refactor/app/helpers/controls_helper.rb
module ControlsHelper
end

helloworld_before_refactor/app/helpers/pages_helper.rb
module PagesHelper
end

helloworld_before_refactor/app/helpers/products_helper.rb
module ProductsHelper
end

helloworld_before_refactor/app/helpers/sql_query_helper.rb
module SqlQueryHelper
	def form_query
		sql = "
		  SELECT * 
		  FROM contact_forms
		"
        @forms = ActiveRecord::Base.connection.exec_query(sql)
	end
end

helloworld_before_refactor/app/views/products/_form.html.erb
<form action="/products" method="post" id="new_product" class="new_product">

  <div class="field">
       
    <label for="prodcut_name">
      Name
    </label><br>

    <input type="text" name="product[name]" id="product_name">

  </div>

  <div class="field">
       
    <label for="prodcut_sku">
      SKU
    </label><br>

    <input type="text" name="product[sku]" id="product_sku">

  </div>

  <div class="field">
       
    <label for="prodcut_description">
      Description
    </label><br>

    <input type="text" name="product[description]" id="product_description">

  </div><br>
    

  <div class="actions">
    <input type="submit" name="commit" value="Confirm Product Create">
  </div>

</form>

helloworld_before_refactor/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

helloworld_before_refactor/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sku</th>
      <th>Description</th>
      <th>Ost</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.sku %></td>
        <td><%= product.description %></td>
        <td><%= product.ost_id %></td>
        <td><%= product.priority %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %><br>

<%= params %>

helloworld_before_refactor/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

helloworld_before_refactor/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Ost:</strong>
  <%= @product.ost_id %>
</p>