helloworld_before_refactor/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :subscriptions
  resources :contact_forms

  root 'modules#index', as: :modules

   get  '/mod_user' => 'application#mod_user'

   post "/controls/new" => "subscriptions#create"

   get '/subscribe' => 'controls#new'
   post '/subscribe' => 'controls#new'

   get '/subscribers' => 'controls#index'

   post '/subscriptions/new' => 'subscriptions#create'

   get '/product' => 'products#show'

   get ':id', to: 'modules#show', as: :module

end

helloworld_before_refactor/app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
	belongs_to :subject

	validates :full_name, presence: true
	validates :order_num, presence: true, length: { minimum: 2 }
	validates :comments, presence: true
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "invalid format"}, presence: true
end

helloworld_before_refactor/app/models/control.rb
class Control < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	attr_accessor :marker

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/product.rb
class Product < ActiveRecord::Base
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :contact_forms
end

helloworld_before_refactor/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/sys_rln_sya_sym.rb
class SysRlnSyaSym < ActiveRecord::Base
	self.table_name = "sys_rln_sya_sym"
	belongs_to :sys_sym_module, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	belongs_to :sys_sya_account, :foreign_key => :rln_sya_id, :primary_key => :sya_id
end

helloworld_before_refactor/app/models/sys_sla_log_action.rb
class SysSlaLogAction < ActiveRecord::Base
	self.table_name = "sys_sla_log_action"
end

helloworld_before_refactor/app/models/sys_sle_log_error.rb
class SysSleLogError < ActiveRecord::Base
	self.table_name = "sys_sle_log_error"
end

helloworld_before_refactor/app/models/sys_sls_log_security.rb
class SysSlsLogSecurity < ActiveRecord::Base
	self.table_name = "sys_sls_log_security"
end

helloworld_before_refactor/app/models/sys_ste_site.rb
class SysSteSite < ActiveRecord::Base
	self.table_name = "sys_ste_site"
end

helloworld_before_refactor/app/models/sys_stx_text_label.rb
class SysStxTextLabel < ActiveRecord::Base
	self.table_name = "sys_stx_text_label"
end

helloworld_before_refactor/app/models/sys_sya_account.rb
class SysSyaAccount < ActiveRecord::Base
	self.table_name = "sys_sya_account"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sya_id, :primary_key => :sya_id
	has_many :sys_sym_modules, :through => :sys_rln_sya_syms
end

helloworld_before_refactor/app/models/sys_sym_module.rb
class SysSymModule < ActiveRecord::Base
	self.table_name = "sys_sym_module"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	has_many :sys_sya_accounts, :through => :sys_rln_sya_syms

	def to_param
		"module#{id}"
	end

end

helloworld_before_refactor/app/models/sys_syw_whitelist.rb
class SysSywWhitelist < ActiveRecord::Base
	self.table_name = "sys_syw_whitelist"
end

helloworld_before_refactor/app/models/tst_dmo_demo.rb
class TstDmoDemo < ActiveRecord::Base
	self.table_name = "tst_dmo_demo"
end

helloworld_before_refactor/app/models/tst_exp_example.rb
class TstExpExample < ActiveRecord::Base
	self.table_name = "tst_exp_example"
end

helloworld_before_refactor/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    lists = [] 
    @subscriptions.each do |subscription| 
      lists << subscription.list
    end 

    @lists = lists.uniq

    @demos = TstDmoDemo.all

    @examples = TstExpExample.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.save

    redirect_to subscriptions_path
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email, :name, :list)
    end
end

helloworld_before_refactor/app/helpers/application_helper.rb
module ApplicationHelper
	
end

helloworld_before_refactor/app/helpers/controls_helper.rb
module ControlsHelper
end

helloworld_before_refactor/app/helpers/pages_helper.rb
module PagesHelper
end

helloworld_before_refactor/app/helpers/products_helper.rb
module ProductsHelper
end

helloworld_before_refactor/app/helpers/sql_query_helper.rb
module SqlQueryHelper
	def form_query
		sql = "
		  SELECT * 
		  FROM contact_forms
		"
        @forms = ActiveRecord::Base.connection.exec_query(sql)
	end
end

helloworld_before_refactor/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

helloworld_before_refactor/app/views/subscriptions/_form.html.erb
<h2>With Name Subscription</h2>

<form action="/subscriptions/new" method="post" id="new_subscription" class="new_subscription">
    
    <input value="With Name" type="hidden" name="subscription[list]" id="subscritpion_list">

    <div class="field">
      <label for="subscription_email">
        Email
      </label><br>
      <input type="text" name="subscription[email]" id="subscription_email">
    </div>
    
    <div class="field">
      <label for="subscription_email">
        Name
      </label><br>
      <input type="text" name="subscription[name]" id="subscription_name">
    </div>
    
    <div class="actions">
      <input type="submit" name="commit" value="Create Subscription">
    </div>

</form>

<h2>Without Name Subscription</h2>

<form action="/subscriptions/new" method="post" id="new_subscription" class="new_subscription">
    
    <input value="Without Name" type="hidden" name="subscription[list]" id="subscritpion_list">

    <div class="field">
      <label for="subscription_email">
        Email
      </label><br>
      <input type="text" name="subscription[email]" id="subscription_email">
    </div>
    
    <div class="field">
      <label for="subscription_email">
        Name
      </label><br>
      <input type="text" name="subscription[name]" id="subscription_name">
    </div>
    
    <div class="actions">
      <input type="submit" name="commit" value="Create Subscription">
    </div>

</form>

helloworld_before_refactor/app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

helloworld_before_refactor/app/views/subscriptions/index.html.erb
<!-- Logic -->

<% status_pending = 1 %>
<% status_active = 2 %>
<% status_deleted = 3 %>

<% status = status_active %>

<% lists = @subscriptions.select("DISTINCT list").where(:ost_id => status) %>

<!-- Display -->

<p id="notice"><%= notice %></p>

<h2>Lists</h2>

<table>
  <thead>
    <tr>
      <th>List Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
   
  <% lists.each do |i| %>

    <% count = "(" + @subscriptions.select("DISTINCT email").where(:list => i.list).where(:ost_id => status).count.to_s + ")" %>

    <tr>
      <td>
        <%= i.list %>
      </td>
      <td>
        <%= count %>
      </td>
    </tr>

  <% end %>
  </tbody>
</table>

<br>

<h2>Subscriptions</h2>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>List</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= subscription.name %></td>
        <td><%= subscription.list %></td>
        <td><%= subscription.ost_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Demos</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.dmo_name %></td>
        <td><%= demo.dmo_value %></td>
        <td><%= demo.dmo_price %></td>
        <td><%= demo.dmo_ost_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>
   

<%= link_to 'New Subscription', new_subscription_path %>

helloworld_before_refactor/app/views/subscriptions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

helloworld_before_refactor/app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>List:</strong>
  <%= @subscription.list %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>