helloworld_before_refactor/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :subscriptions
  resources :contact_forms

  root 'modules#index', as: :modules

   get  '/mod_user' => 'application#mod_user'

   post "/controls/new" => "subscriptions#create"

   get '/subscribe' => 'controls#new'
   post '/subscribe' => 'controls#new'

   get '/subscribers' => 'controls#index'

   post '/subscriptions/new' => 'subscriptions#create'

   get '/product' => 'products#show'

   get ':id', to: 'modules#show', as: :module

end

helloworld_before_refactor/app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
	belongs_to :subject

	validates :full_name, presence: true
	validates :order_num, presence: true, length: { minimum: 2 }
	validates :comments, presence: true
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "invalid format"}, presence: true
end

helloworld_before_refactor/app/models/control.rb
class Control < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	attr_accessor :marker

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/product.rb
class Product < ActiveRecord::Base
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :contact_forms
end

helloworld_before_refactor/app/models/subscription.rb
class Subscription < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true, length: { minimum: 2 }
	
	before_create :status_assign

	def status_assign
		self.ost_id = 2
	end
end

helloworld_before_refactor/app/models/sys_rln_sya_sym.rb
class SysRlnSyaSym < ActiveRecord::Base
	self.table_name = "sys_rln_sya_sym"
	belongs_to :sys_sym_module, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	belongs_to :sys_sya_account, :foreign_key => :rln_sya_id, :primary_key => :sya_id
end

helloworld_before_refactor/app/models/sys_sla_log_action.rb
class SysSlaLogAction < ActiveRecord::Base
	self.table_name = "sys_sla_log_action"
end

helloworld_before_refactor/app/models/sys_sle_log_error.rb
class SysSleLogError < ActiveRecord::Base
	self.table_name = "sys_sle_log_error"
end

helloworld_before_refactor/app/models/sys_ste_site.rb
class SysSteSite < ActiveRecord::Base
	self.table_name = "sys_ste_site"
end

helloworld_before_refactor/app/models/sys_stx_text_label.rb
class SysStxTextLabel < ActiveRecord::Base
	self.table_name = "sys_stx_text_label"
end

helloworld_before_refactor/app/models/sys_sya_account.rb
class SysSyaAccount < ActiveRecord::Base
	self.table_name = "sys_sya_account"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sya_id, :primary_key => :sya_id
	has_many :sys_sym_modules, :through => :sys_rln_sya_syms
end

helloworld_before_refactor/app/models/sys_sym_module.rb
class SysSymModule < ActiveRecord::Base
	self.table_name = "sys_sym_module"
	has_many :sys_rln_sya_syms, :foreign_key => :rln_sym_id, :primary_key => :sym_id
	has_many :sys_sya_accounts, :through => :sys_rln_sya_syms

	def to_param
		"module#{id}"
	end

end

helloworld_before_refactor/app/models/sys_syw_whitelist.rb
class SysSywWhitelist < ActiveRecord::Base
	self.table_name = "sys_syw_whitelist"
end

helloworld_before_refactor/app/models/tst_dmo_demo.rb
class TstDmoDemo < ActiveRecord::Base
	self.table_name = "tst_dmo_demo"
end

helloworld_before_refactor/app/models/tst_exp_example.rb
class TstExpExample < ActiveRecord::Base
	self.table_name = "tst_exp_example"
end

helloworld_before_refactor/app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  before_action :set_contact_form, only: [:show, :edit, :update, :destroy]

  # GET /contact_forms
  # GET /contact_forms.json
  def index
    @contact_forms = ContactForm.all
    
    @sql_contacts = ContactForm.find_by_sql("
      SELECT * 
      FROM  contact_forms
    ")

    sql = "SELECT * FROM contact_forms"
    @sql = ActiveRecord::Base.connection.exec_query(sql)
  end

  # GET /contact_forms/1
  # GET /contact_forms/1.json
  def show
  end

  def page

  # GET /contact_forms/new
  def new
    @contact_form = ContactForm.new
    @subjects = Subject.all
  end

  # GET /contact_forms/1/edit
  def edit
  end

  # POST /contact_forms
  # POST /contact_forms.json
  def create
    @contact_form = ContactForm.new(contact_form_params)

    respond_to do |format|
      if @contact_form.save
        ContactMailer.contact_email(@contact_form).deliver
        format.html { redirect_to @contact_form, notice: 'Contact form was successfully created.' }
        format.json { render :show, status: :created, location: @contact_form }
      else
        format.html { render :new }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_forms/1
  # PATCH/PUT /contact_forms/1.json
  def update
    respond_to do |format|
      if @contact_form.update(contact_form_params)
        format.html { redirect_to @contact_form, notice: 'Contact form was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_form }
      else
        format.html { render :edit }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_forms/1
  # DELETE /contact_forms/1.json
  def destroy
    @contact_form.destroy
    respond_to do |format|
      format.html { redirect_to contact_forms_url, notice: 'Contact form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mod_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_form
      @contact_form = ContactForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_form_params
      params.require(:contact_form).permit(:full_name, :email, :order_num, :comments, :subject_id)
    end
end
end

helloworld_before_refactor/app/helpers/application_helper.rb
module ApplicationHelper
	
end

helloworld_before_refactor/app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

helloworld_before_refactor/app/helpers/controls_helper.rb
module ControlsHelper
end

helloworld_before_refactor/app/helpers/pages_helper.rb
module PagesHelper
end

helloworld_before_refactor/app/helpers/products_helper.rb
module ProductsHelper
end

helloworld_before_refactor/app/helpers/sql_query_helper.rb
module SqlQueryHelper
	def form_query
		sql = "
		  SELECT * 
		  FROM contact_forms
		"
        @forms = ActiveRecord::Base.connection.exec_query(sql)
	end
end

helloworld_before_refactor/app/views/contact_forms/_body.html.erb
<div style="width:100%; height: 400px; background-color:orange; position:relative">
	<div style="margin:auto; width:50%; position:absolute; left:2px; margin-top:60px; height:250px; background-color:green">
		<p style="margin:auto; width:25em; padding-top:30px">
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
		</p>
	</div>
</div>

helloworld_before_refactor/app/views/contact_forms/_footer.html.erb
<div style="width:100%; height: 200px; background-color:black; position:relative">
	<div style="display:inline-block; width:200px; height:100%; position:absolute; left:42%; background-color:pink">
		<table class="carp">
		  <thead stlye="border: 1px solid black">
		    
		    <tr>
		      <th>
		      	Column 1
		      </th>
		      <th>
		      	Column 2
		      </th>
		      <th>
		      	Column 3
		      </th>
		    </tr>

		  </thead>

		  <tbody stlye="border: 1px solid black">
	    	
	    	<tr>
		        <td>value 1</td>
		        <td>value 2</td>
		        <td>value 3</td>
	      	</tr>
		    
		  </tbody>
		</table>
    </div>
</div>

helloworld_before_refactor/app/views/contact_forms/_form.html.erb
<% @contact_form = ContactForm.new %>

<%= form_for @contact_form do |f| %>
  <% if @contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

      <ul>
      <% @contact_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="new_contact_form" id="new_contact_form" action="/contact_forms" accept-charset="UTF-8" method="post">
    
    <div class="field">
      <label for="contact_form_full_name">
        Full Name
      </label><br>
      <input placeholder="ex: joe@joe.com" type="text" name="contact_form[full_name]" id="contact_form_full_name">
    </div>
    
    <div class="field">
      <label for="contact_form_email">
        Email
      </label><br>
      <input type="text" name="contact_form[email]" id="contact_form_email">
    </div>
    
    <div class="field">
      <label for="contact_form_order_num">
        Order Num
      </label><br>
      <input type="text" name="contact_form[order_num]" id="contact_form_order_num">
    </div>
    
    <div class="field">
      <label for="contact_form_comments">
        Comments
      </label><br>
      <textarea type="text" name="contact_form[comments]" id="contact_form_comments"></textarea>
    </div>
    
    <div class="field">
      <label for="contact_form_subject">
        Subject
      </label><br>
      <select name="contact_form[subject_id]" id="contact_form_comments">
        <% Subject.order('priority ASC').each do |x| %>
          <option value=<%=x.id%>>
            <%= x.name%>
          </option>
        <% end %>
      </select>
    </div>
    
    <div class="actions">
      <input type="submit" name="commit" value="Create Contact Form">
    </div>
  </form>
<% end %>

<h2>Placeholder Contact Form</h2>

<%= form_for(@contact_form) do |f| %>
  <% if @contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

      <ul>
      <% @contact_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="new_contact_form" id="new_contact_form" action="/contact_forms" accept-charset="UTF-8" method="post">
    
    <div class="field">
      <label for="contact_form_full_name">
        Full Name
      </label><br>
      <input placeholder="Full Name" type="text" name="contact_form[full_name]" id="contact_form_full_name">
    </div>
    
    <div class="field">
      <label for="contact_form_email">
        Email
      </label><br>
      <input placeholder="Email" type="text" name="contact_form[email]" id="contact_form_email">
    </div>
    
    <div class="field">
      <label for="contact_form_order_num">
        Order Num
      </label><br>
      <input placeholder="Order Number" type="text" name="contact_form[order_num]" id="contact_form_order_num">
    </div>
    
    <div class="field">
      <label for="contact_form_comments">
        Comments
      </label><br>
      <textarea placeholder="enter comments here" type="text" name="contact_form[comments]" id="contact_form_comments"></textarea>
    </div>
    
    <div class="field">
      <label for="contact_form_subject">
        Subject
      </label><br>
      <select name="contact_form[subject_id]" id="contact_form_comments">
        <% Subject.order('priority ASC').each do |x| %>
          <option value=<%=x.id%>>
            <%= x.name%>
          </option>
        <% end %>
      </select>
    </div>
    
    <div class="actions">
      <input type="submit" name="commit" value="Create Contact Form">
    </div>

  </form>
<% end %>

<h2>Stylized labels and placholder hints</h2>

<%= form_for(@contact_form) do |f| %>
  <% if @contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

      <ul>
      <% @contact_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="new_contact_form" id="new_contact_form" action="/contact_forms" accept-charset="UTF-8" method="post">
    
    <div class="field">
      <label for="contact_form_full_name" class="label">
        Full Name
      </label><br>
      <input placeholder="Full Name" type="text" name="contact_form[full_name]" id="contact_form_full_name">
    </div>
    
    <div class="field">
      <label for="contact_form_email" class="label">
        Email
      </label><br>
      <input placeholder="Email" type="text" name="contact_form[email]" id="contact_form_email">
    </div>
    
    <div class="field">
      <label for="contact_form_order_num" class="label">
        Order Num
      </label><br>
      <input placeholder="Order Number" type="text" name="contact_form[order_num]" id="contact_form_order_num">
    </div>
    
    <div class="field">
      <label for="contact_form_comments" class="label">
        Comments
      </label><br>
      <textarea placeholder="enter comments here" type="text" name="contact_form[comments]" id="contact_form_comments"></textarea>
    </div>
    
    <div class="field">
      <label for="contact_form_subject" class="label">
        Subject
      </label><br>
      <select name="contact_form[subject_id]" id="contact_form_comments">
        <% Subject.order('priority ASC').each do |x| %>
          <option value=<%=x.id%>>
            <%= x.name%>
          </option>
        <% end %>
      </select>
    </div>
    
    <div class="actions">
      <input type="submit" name="commit" value="Create Contact Form">
    </div>

  </form>
<% end %>

  <h2>Aria Label Attributes</h2>

<%= form_for(@contact_form) do |f| %>
  <% if @contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

      <ul>
      <% @contact_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="new_contact_form" id="new_contact_form" action="/contact_forms" accept-charset="UTF-8" method="post">
    
    <div class="field">
      <label for="contact_form_full_name" class="label">
        Full Name
      </label><br>
      <input placeholder="Full Name" type="text" name="contact_form[full_name]" id="contact_form_full_name" aria-label="value" aria-invalid='false'>
    </div>
    
    <div class="field">
      <label for="contact_form_email" class="label">
        Email
      </label><br>
      <input placeholder="Email" type="text" name="contact_form[email]" id="contact_form_email" aria-label="value" aria-invalid='false'>
    </div>
    
    <div class="field">
      <label for="contact_form_order_num" class="label">
        Order Num
      </label><br>
      <input placeholder="Order Number" type="text" name="contact_form[order_num]" id="contact_form_order_num" aria-label="value" aria-invalid='false'>
    </div>
    
    <div class="field">
      <label for="contact_form_comments" class="label">
        Comments
      </label><br>
      <textarea placeholder="enter comments here" type="text" name="contact_form[comments]" id="contact_form_comments" aria-label="value" aria-invalid='false'></textarea>
    </div>
    
    <div class="field">
      <label for="contact_form_subject" class="label">
        Subject
      </label><br>
      <select name="contact_form[subject_id]" id="contact_form_comments" aria-label="value" aria-invalid='false'>
        <% Subject.order('priority ASC').each do |x| %>
          <option value=<%=x.id%>>
            <%= x.name%>
          </option>
        <% end %>
      </select>
    </div>
    
    <div class="actions">
      <input type="submit" name="commit" value="Create Contact Form">
    </div>
    
  </form>
<% end %>

helloworld_before_refactor/app/views/contact_forms/_header.html.erb
<div style="width:100%; height: 50px; background-color:black; position:relative">
	<div style="display:inline-block; width:100px; height:100%; position:absolute; left:50px; background-color:pink">
		<p>
			Logo
		</p>
    </div>
    <div style="display:inline-block; width:100px; height:100%; background-color:blue; position:absolute; right:50px">
		<p style="color:white">
			Menu
		</p>
    </div>
</div>

<div style="width:100%; height: 50px; background-color:purple; position:relative">
	<p style="color:white; margin:auto; margin-left: 48%; padding-top:12px">
		Banner
	</p>
</div>

helloworld_before_refactor/app/views/contact_forms/edit.html.erb
<h1>Editing Contact Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_form %> |
<%= link_to 'Back', contact_forms_path %>

helloworld_before_refactor/app/views/contact_forms/index.html.erb
<p id="notice"><%= notice %></p>
<p><%= Time.now.strftime('%H:%M:%S.%L')  %></p>
<h1>Listing Contact Forms</h1>

<% form_query %>

<p>
  <%= @forms.each do |x| puts x end %>
</p>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Order num</th>
      <th>Comments</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sql.each do |contact_form| %>
      <tr>
        <td><%= contact_form["full_name"] %></td>
        <td><%= contact_form["email"] %></td>
        <td><%= contact_form["order_num"] %></td>
        <td><%= contact_form["comments"] %></td>

        <% subject = ActiveRecord::Base.connection.exec_query("
            SELECT name 
            FROM subjects 
            WHERE [subjects].[id] = #{contact_form['subject_id']}
            ").first
        %>

        <td><%= subject["name"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact form', new_contact_form_path %>

<% sql = "SELECT [contact_forms].* FROM [contact_forms]" %>

<p><%=  ActiveRecord::Base.connection.exec_query(sql).each do |x| puts x end %></p>

<p><%= Time.now.strftime('%H:%M:%S.%L')  %></p>

helloworld_before_refactor/app/views/contact_forms/module_user.html.erb
<%= render 'header' %>

<%= render 'body' %>

<%= render 'footer' %>

helloworld_before_refactor/app/views/contact_forms/new.html.erb
<h1>New Contact Form</h1>

<%= render 'form' %>

helloworld_before_refactor/app/views/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @contact_form.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_form.email %>
</p>

<p>
  <strong>Order num:</strong>
  <%= @contact_form.order_num %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @contact_form.comments %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact_form.subject %>
</p>

<%= link_to 'New Contact Form', new_contact_form_path %> 